import { Sudoku } from './Sudoku';

export const SudokuExample: Sudoku = {
  rows: [
    {
      location: 1,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: 4, preset: true },
            { location: 2, value: 3, preset: true },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: 1, preset: true },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: 8, preset: true },
            { location: 7, value: 5, preset: true },
            { location: 8, value: 9, preset: true },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: 6, preset: true },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: 7, preset: true },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
      ],
    },
    {
      location: 2,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: 8, preset: true },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: 1, preset: true },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: 7, preset: true },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: 2, preset: true },
            { location: 7, value: 8, preset: true },
            { location: 8, value: 3, preset: true },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: 3, preset: true },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: 4, preset: true },
          ],
        },
      ],
    },
    {
      location: 3,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: 5, preset: true },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: 9, preset: true },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: 2, preset: true },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: 3, preset: true },
            { location: 5, value: 1, preset: true },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: 9, preset: true },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: 7, preset: true },
          ],
        },
      ],
    },
  ],
};

export const SudokuExampleSolved: Sudoku = {
  rows: [
    {
      location: 1,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: 4, preset: true },
            { location: 2, value: 3, preset: true },
            { location: 3, value: 9, preset: false },
            { location: 4, value: 5, preset: false },
            { location: 5, value: 7, preset: false },
            { location: 6, value: 2, preset: false },
            { location: 7, value: 8, preset: false },
            { location: 8, value: 6, preset: false },
            { location: 9, value: 1, preset: true },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: 2, preset: false },
            { location: 2, value: 7, preset: false },
            { location: 3, value: 1, preset: false },
            { location: 4, value: 4, preset: false },
            { location: 5, value: 6, preset: false },
            { location: 6, value: 8, preset: false },
            { location: 7, value: 5, preset: false },
            { location: 8, value: 9, preset: false },
            { location: 9, value: 3, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: 8, preset: false },
            { location: 2, value: 6, preset: false },
            { location: 3, value: 5, preset: false },
            { location: 4, value: 1, preset: false },
            { location: 5, value: 3, preset: false },
            { location: 6, value: 9, preset: false },
            { location: 7, value: 7, preset: false },
            { location: 8, value: 4, preset: false },
            { location: 9, value: 2, preset: false },
          ],
        },
      ],
    },
    {
      location: 2,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: 3, preset: false },
            { location: 2, value: 2, preset: false },
            { location: 3, value: 8, preset: false },
            { location: 4, value: 9, preset: false },
            { location: 5, value: 4, preset: false },
            { location: 6, value: 6, preset: false },
            { location: 7, value: 1, preset: false },
            { location: 8, value: 5, preset: false },
            { location: 9, value: 7, preset: false },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: 9, preset: false },
            { location: 2, value: 4, preset: false },
            { location: 3, value: 7, preset: false },
            { location: 4, value: 1, preset: false },
            { location: 5, value: 5, preset: false },
            { location: 6, value: 2, preset: false },
            { location: 7, value: 8, preset: false },
            { location: 8, value: 3, preset: false },
            { location: 9, value: 6, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: 6, preset: false },
            { location: 2, value: 5, preset: false },
            { location: 3, value: 1, preset: false },
            { location: 4, value: 3, preset: false },
            { location: 5, value: 7, preset: false },
            { location: 6, value: 8, preset: false },
            { location: 7, value: 2, preset: false },
            { location: 8, value: 9, preset: false },
            { location: 9, value: 4, preset: false },
          ],
        },
      ],
    },
    {
      location: 3,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: 6, preset: false },
            { location: 2, value: 1, preset: false },
            { location: 3, value: 4, preset: false },
            { location: 4, value: 7, preset: false },
            { location: 5, value: 8, preset: false },
            { location: 6, value: 5, preset: false },
            { location: 7, value: 2, preset: false },
            { location: 8, value: 9, preset: false },
            { location: 9, value: 3, preset: false },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: 7, preset: false },
            { location: 2, value: 2, preset: false },
            { location: 3, value: 9, preset: false },
            { location: 4, value: 3, preset: false },
            { location: 5, value: 1, preset: false },
            { location: 6, value: 4, preset: false },
            { location: 7, value: 6, preset: false },
            { location: 8, value: 8, preset: false },
            { location: 9, value: 5, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: 5, preset: false },
            { location: 2, value: 8, preset: false },
            { location: 3, value: 3, preset: false },
            { location: 4, value: 9, preset: false },
            { location: 5, value: 2, preset: false },
            { location: 6, value: 6, preset: false },
            { location: 7, value: 4, preset: false },
            { location: 8, value: 1, preset: false },
            { location: 9, value: 7, preset: false },
          ],
        },
      ],
    },
  ],
};

export const EmptySudokuExample: Sudoku = {
  rows: [
    {
      location: 1,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: undefined, preset: true },
            { location: 2, value: undefined, preset: true },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: true },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
      ],
    },
    {
      location: 2,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
      ],
    },
    {
      location: 3,
      sections: [
        {
          location: 1,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 2,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
        {
          location: 3,
          cells: [
            { location: 1, value: undefined, preset: false },
            { location: 2, value: undefined, preset: false },
            { location: 3, value: undefined, preset: false },
            { location: 4, value: undefined, preset: false },
            { location: 5, value: undefined, preset: false },
            { location: 6, value: undefined, preset: false },
            { location: 7, value: undefined, preset: false },
            { location: 8, value: undefined, preset: false },
            { location: 9, value: undefined, preset: false },
          ],
        },
      ],
    },
  ],
};
